version: 2
# orbs:
#   codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:

      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:

      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout


      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-gradle-cache-{{ checksum "build.gradle" }}

      - save_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - ~/.gradle/wrapper
      - save_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle/caches

      - run: gradle test
      - store_artifacts:
          path:  build/jacoco/